// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CitationController from "./citation_controller"
application.register("citation", CitationController)

import CommunityDropdownController from "./community_dropdown_controller"
application.register("community-dropdown", CommunityDropdownController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)
