// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Charts__AgeDistributionController from "./charts/age_distribution_controller"
application.register("charts--age-distribution", Charts__AgeDistributionController)

import Charts__BaseController from "./charts/base_controller"
application.register("charts--base", Charts__BaseController)

import Charts__ElectricityConsumptionBySectorController from "./charts/electricity_consumption_by_sector_controller"
application.register("charts--electricity-consumption-by-sector", Charts__ElectricityConsumptionBySectorController)

import Charts__ElectricityConsumptionController from "./charts/electricity_consumption_controller"
application.register("charts--electricity-consumption", Charts__ElectricityConsumptionController)

import Charts__ElectricityCustomersController from "./charts/electricity_customers_controller"
application.register("charts--electricity-customers", Charts__ElectricityCustomersController)

import Charts__ElectricityRevenueController from "./charts/electricity_revenue_controller"
application.register("charts--electricity-revenue", Charts__ElectricityRevenueController)

import Charts__FuelController from "./charts/fuel_controller"
application.register("charts--fuel", Charts__FuelController)

import Charts__SexDistributionController from "./charts/sex_distribution_controller"
application.register("charts--sex-distribution", Charts__SexDistributionController)

import Charts__YearlyElectricRatesController from "./charts/yearly_electric_rates_controller"
application.register("charts--yearly-electric-rates", Charts__YearlyElectricRatesController)

import Charts__YearlyGenerationController from "./charts/yearly_generation_controller"
application.register("charts--yearly-generation", Charts__YearlyGenerationController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ScrollspyController from "./scrollspy_controller"
application.register("scrollspy", ScrollspyController)

import SearchPanelsController from "./search_panels_controller"
application.register("search-panels", SearchPanelsController)

import SplitLayoutController from "./split_layout_controller"
application.register("split-layout", SplitLayoutController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TurboActiveLinkController from "./turbo_active_link_controller"
application.register("turbo-active-link", TurboActiveLinkController)

import WidgetUpdateController from "./widget_update_controller"
application.register("widget-update", WidgetUpdateController)
