// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgeDistributionChartController from "./age_distribution_chart_controller"
application.register("age-distribution-chart", AgeDistributionChartController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ElectricityConsumptionBySectorChartController from "./electricity_consumption_by_sector_chart_controller"
application.register("electricity-consumption-by-sector-chart", ElectricityConsumptionBySectorChartController)

import ElectricityConsumptionChartController from "./electricity_consumption_chart_controller"
application.register("electricity-consumption-chart", ElectricityConsumptionChartController)

import ElectricityCustomersChartController from "./electricity_customers_chart_controller"
application.register("electricity-customers-chart", ElectricityCustomersChartController)

import ElectricityRevenueChartController from "./electricity_revenue_chart_controller"
application.register("electricity-revenue-chart", ElectricityRevenueChartController)

import FuelChartController from "./fuel_chart_controller"
application.register("fuel-chart", FuelChartController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ScrollspyController from "./scrollspy_controller"
application.register("scrollspy", ScrollspyController)

import SearchPanelsController from "./search_panels_controller"
application.register("search-panels", SearchPanelsController)

import SexDistributionChartController from "./sex_distribution_chart_controller"
application.register("sex-distribution-chart", SexDistributionChartController)

import StickyOffsetController from "./sticky_offset_controller"
application.register("sticky-offset", StickyOffsetController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TurboActiveLinkController from "./turbo_active_link_controller"
application.register("turbo-active-link", TurboActiveLinkController)

import WidgetUpdateController from "./widget_update_controller"
application.register("widget-update", WidgetUpdateController)

import YearlyElectricRatesChartController from "./yearly_electric_rates_chart_controller"
application.register("yearly-electric-rates-chart", YearlyElectricRatesChartController)

import YearlyGenerationChartController from "./yearly_generation_chart_controller"
application.register("yearly-generation-chart", YearlyGenerationChartController)
