inherit_from: .rubocop_todo.yml

plugins: rubocop-rails

AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'    
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    
Style/FrozenStringLiteralComment:
  Enabled: false
