CREATE TABLE gaz2024(
    USPS VARCHAR,
    GEOID VARCHAR,
    ANSICODE VARCHAR,
    "NAME" VARCHAR,
    LSAD BIGINT,
    FUNCSTAT VARCHAR,
    ALAND BIGINT,
    AWATER BIGINT,
    ALAND_SQMI DOUBLE PRECISION,
    AWATER_SQMI DOUBLE PRECISION,
    INTPTLAT DOUBLE PRECISION,
    INTPTLONG VARCHAR);